name: Android CI
on:
  push:
    branches:
      - 'master'
    
jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Assemble debug
        run: ./gradlew assembleDebug
      - name: Upload debug apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: DebugApk
          path: app/build/outputs/apk/debug/
       