name: Android CI
on:
  push:
    branches:
      - 'master'
    
jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Assemble debug
        run: ./gradlew assembleDebug
      - name: Upload debug apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: DebugApk
          path: app/build/outputs/apk/debug/

  build-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Assemble release
        run: ./gradlew assembleRelease
      - name: Sign release apk
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Generate release tag
        id: tagnamegen
        run: |
          echo "::set-output name=release_tag::YaShaderEditor_$(date +"%Y.%m.%d_%H-%M")"
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tagnamegen.outputs.release_tag }}
          files: ${{steps.sign_apk.outputs.signedReleaseFile}}